server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

users-api:
  url: https://cgjresszgg.execute-api.eu-west-1.amazonaws.com/users/
teams-api:
  url: https://cgjresszgg.execute-api.eu-west-1.amazonaws.com/teams/
